[en]
label = "English"
direction = "ltr"
title = "Ana García's Space"
weight = 1

[es]
label = "Español"
direction = "ltr"
title = "La Web de Ana García"
weight = 2

[es.params]
[es.params.sidebar]
subtitle = "¡Bienvenido a mi página web! Me encanta crear contenido y escribir algunas de mis opiniones, así que este es el hueco que me he creado en la web."

[es.params.dateFormat]
published = "02/01/2006"
lastUpdated = "02/01/2006 15:04 CET"

[es.params.footer]
customText = "<a class=\"footer-highlight-link\" href=\"/es/privacy-policy/\">Política de Privacidad</a>"
